'use strict';
const creatives=window.CREATIVE_DATA||[];
const creativeNames=new Map();
for(const creative of creatives){const list=creativeNames.get(creative.name)||[];list.push(creative);creativeNames.set(creative.name,list)}
function creativeMatches(r){return r.adId?creatives.filter(c=>c.adId===r.adId):(creativeNames.get(r.name)||[])}
function safeCreativeURL(value){try{const url=new URL(value);return ['https:','http:'].includes(url.protocol)?url.href:''}catch{return ''}}
function creativeLink(label,url){const href=safeCreativeURL(url);return href?`<a class="creative-external" href="${esc(href)}" target="_blank" rel="noopener noreferrer">${esc(label)} ↗</a>`:''}
let creativeSearch='',creativePage=0,creativePlacement='Facebook Feed';
function showCreativeLibrary(){const q=creativeSearch.toLowerCase();const rows=creatives.filter(c=>[c.name,c.adId,c.campaignName,c.adsetName,c.copy].some(v=>(v||'').toLowerCase().includes(q)));const page=rows.slice(creativePage*40,creativePage*40+40);drawer('Ad creative library',`<div class="creative-library"><p class="muted">${creatives.length.toLocaleString()} exported ads · Source snapshot: ${esc(company.snapshotDate)}</p><input id="creative-search" aria-label="Search ad creative library" placeholder="Search ad name, ID, campaign, ad set or text" value="${esc(creativeSearch)}"><p>${rows.length.toLocaleString()} matching ads</p><div class="creative-list">${page.map(c=>`<button class="creative-item" data-action="creative-open:${esc(c.adId)}">${c.image?`<img loading="lazy" src="${esc(c.image)}" alt="">`:'<span class="creative-no-image">Ad</span>'}<span><b>${esc(c.name)}</b><small>${esc(c.campaignName)} › ${esc(c.adsetName)}</small><small>${esc(c.adId)}</small></span><span>›</span></button>`).join('')}</div><div class="creative-pagination">${btn('Previous','creative-page:-1','','',creativePage===0?'disabled':'')}<span>Page ${creativePage+1} of ${Math.max(1,Math.ceil(rows.length/40))}</span>${btn('Next','creative-page:1','','',(creativePage+1)*40>=rows.length?'disabled':'')}</div><p class="muted small">Meta excluded ads using multiple text or headline variants. Spending ads are matched by verified ad IDs; duplicate names are not automatically matched.</p></div>`)}
function showSourceCreative(c){const page=c.page||`Page ${String(c.pageId||'').replace(/^o:/,'')}`;drawer('Ad preview',`<div class="source-preview-layout"><div class="preview-controls">${btn('‹ All creatives','creative-library')}<label>Placement <select id="creative-placement">${['Facebook Feed','Instagram Feed','Facebook Stories','Instagram Stories','Instagram Reels'].map(p=>`<option ${p===creativePlacement?'selected':''}>${p}</option>`).join('')}</select></label></div><h3>${esc(c.name)}</h3><div class="preview-ad source-ad ${/Stories|Reels/.test(creativePlacement)?'vertical-placement':''}"><div class="ad-copy"><div class="preview-page-icon">${icon('ad')}</div><b>${esc(page)}</b><br><small class="muted">Sponsored · ${esc(creativePlacement)}</small></div><div class="ad-copy source-primary">${c.copy&&c.copy.length>230?`<span>${esc(c.copy.slice(0,230))}…</span><details class="preview-full-copy"><summary>See more</summary>${esc(c.copy)}</details>`:esc(c.copy||'Primary text is unavailable in this export.')}</div>${c.image?`<div class="source-media"><img src="${esc(c.image)}" alt="Exported thumbnail for ${esc(c.name)}">${c.videoId?'<span class="video-indicator">▶ Video thumbnail</span>':''}</div>`:'<div class="ad-placeholder">Media was not included in Meta’s export</div>'}<div class="ad-copy source-destination"><small class="muted">${esc(c.displayLink||c.url||'')}</small><h3>${esc(c.headline||'')}</h3><p>${esc(c.description||'')}</p>${creativeLink((c.cta||'LEARN_MORE').replaceAll('_',' '),c.url)}</div><div class="preview-social">Like　　Comment　　Share</div></div><div class="creative-source-details">${creativeMetricsHTML(c)}<p class="muted">${c.imageSource?esc(c.imageSource)+'. ':''}Local layout preview. The export supplies thumbnails, not playable video files; placement rendering is approximate.</p>${creativeLink('Open original Facebook preview',c.previewUrl)} ${creativeLink('Open original Instagram preview',c.instagramUrl)} ${creativeLink('View original post',c.permalink)}<details><summary>Ad details and source data</summary><dl>${[['Ad ID',c.adId],['Campaign',c.campaignName],['Campaign ID',c.campaignId],['Ad set',c.adsetName],['Ad set ID',c.adsetId],['Status',c.status],['Destination',c.url],['Platforms',c.platforms],['Facebook placements',c.facebookPositions],['Instagram placements',c.instagramPositions],['Video ID',c.videoId]].filter(x=>x[1]).map(([k,v])=>`<dt>${esc(k)}</dt><dd>${esc(v)}</dd>`).join('')}</dl></details></div></div>`);$('#drawer').dataset.creativeId=c.adId}
const originalAdPreview=showAdPreview;
showAdPreview=function(r){if(r.source==='local'){originalAdPreview(r);return}const matches=creativeMatches(r);if(r.adId&&matches.length===1){showSourceCreative(matches[0]);return}if(r.adId&&!matches.length){showSourceCreative({...r,adsetId:'c:'+r['Ad set ID'],campaignId:'cg:'+r['Campaign ID'],adsetName:r['Ad set name'],campaignName:r['Campaign name']});return}if(matches.length>0){drawer('Choose an ad preview',`<p>These exported creatives share this name. Select the campaign and ad set to inspect a possible match. Metrics are not assigned without a verified ID match.</p>${matches.map(c=>`<button class="creative-item" data-action="creative-open:${esc(c.adId)}"><span><b>${esc(c.name)}</b><small>${esc(c.campaignName)} › ${esc(c.adsetName)}</small><small>${esc(c.adId)}</small></span>›</button>`).join('')}`);return}originalAdPreview(r)};
const actionBeforeCreatives=action;
action=function(value,el){if(value==='creative-library'){showCreativeLibrary();return}if(value.startsWith('creative-open:')){const c=creatives.find(c=>c.adId===value.slice(14));if(c)showSourceCreative(c);return}if(value.startsWith('creative-page:')){creativePage=Math.max(0,creativePage+Number(value.slice(14)));showCreativeLibrary();return}return actionBeforeCreatives(value,el)};
const renderBeforeCreatives=render;
render=function(){renderBeforeCreatives();$('#toolbar').insertAdjacentHTML('beforeend',btn('Ad previews','creative-library','image','','aria-label="Open ad creative library"'))};
document.addEventListener('change',e=>{if(e.target.id==='creative-search'){creativeSearch=e.target.value;creativePage=0;showCreativeLibrary()}if(e.target.id==='creative-placement'){creativePlacement=e.target.value;const c=creatives.find(c=>c.adId===$('#drawer').dataset.creativeId);if(c)showSourceCreative(c)}});
render();

function creativeMetricsHTML(c){const rows=reference.ads.filter(r=>r.adId===c.adId);if(rows.length!==1)return '';const r=rows[0];return `<div class="creative-performance"><h3>${esc(company.reportStart)} – ${esc(company.reportEnd)}</h3><div class="metric-cards"><div class="metric-card">Amount spent<strong>${money(r['Amount spent (INR)'])}</strong></div><div class="metric-card">Impressions<strong>${num(r.Impressions)}</strong></div><div class="metric-card">Results<strong>${esc(r.Results||'—')}</strong></div></div><p class="small muted">Performance matched by exported Ad ID ${esc(r['Ad ID'])}.</p></div>`}
